### PR TITLE
Release 10.4.1RC1

### PR DESCRIPTION
**Pull request by HanaGemela**

### CODE REVIEW

**Comment by micbar** [comment]
@jnweiger @HanaGemela @phil-davis

After a long discussion, let us keep it like https://github.com/owncloud-docker/server/pull/180

That means we always keep the `latest` and latest stable tags.

**Review by micbar — CHANGES_REQUESTED** [review]
Let us align with server image

**Review by micbar — APPROVED** [review]

**Review by phil-davis — APPROVED** [review]
LGTM

**Comment by jnweiger** [comment]
All 3 docker images are built and uploaded:
```
docker run -ti -v 8080:8080 owncloud/server:10.4.1-rc1
docker run -ti -v 8080:8080 owncloud/appliance:10.4.1-rc1
docker run -ti -v 8080:8080 registry.owncloud.com/owncloud/enterprise:10.4.1-rc1

**Pull request merged**
